### ISSUE TITLE
[Karazhan] Ghostly Baker Faction Fix.

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#103]
NPC is not spawned in the current version of Karazhan (I am working on respawning the entire instance atm); however, when he is he has the wrong faction ID and appears friendly to players.

```SQL
-- Update Ghostly Baker's faction
Code implemented and being tested
```

**Comment by antisocial89** [comment]
Spawning "Ghostly Baker" in the game results in the NPC being hostile. This seems to be fixed.
