### ISSUE TITLE
Goes out of stealth if pick pocking something

### ISSUE THREAD

**Issue by Shamainy** [antisocial89/RealTBC_Issue_tracker#110]
If I pick pocket a mob I sometimes go out of combat, doesn't say anything like resist, miss. I just end up going out of stealth.

**Comment by nairyo** [comment]
This is totally normal to me, you get a chance to being spotted when pickpocketing. Core-wise, its a random  chance taking in account the difference of level between you and your target.
@Shamainy please confirm
