### ISSUE TITLE
Heroic Key Rep requirements

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#121]
Up until 2.4, the rep requirement should be Revered for the flamewrought key (Horde and Alliance), auchenai key, warpforged key, key of time, and the reservoir key.

```SQL
-- Update rep requirement for heroic keys to revered (Pre 2.4)
Implemented
```

When 2.4 hits, you can use this to update the value to honored.
```SQL
-- Patch 2.4 update rep requirement for heroic keys to honored.
Set to be implemented upon progressive release
```

**YOU NEED TO DELETE YOUR CACHE TO SEE THIS CHANGE**

Suggest to also add these keys to the `playercreateinfo_item` for testing purposes.

**Comment by antisocial89** [comment]
Are these two ID's both supposed to be for Flamewrought keys? That's what they're adding to my inventory:
```LUA
	player:AddItem(30622) -- Flamewrought Key
	player:AddItem(30637) -- Flamewrought Key
```

**Comment by Saben65** [comment]
Yes, they are the only dungeon keys that have a horde and alliance equivalent. The rest come from neutral factions/vendors.

**Comment by antisocial89** [comment]
Good deal then. Added and closed.
