### ISSUE TITLE
Food while Slice and Dice is active can't be used.

### ISSUE THREAD

**Issue by Shamainy** [antisocial89/RealTBC_Issue_tracker#124]
While you have SnD active and try to eat food you get a message saying "That can't be used yet" and the food also disapears.

**Comment by nairyo** [comment]
fixed in latest version apparently
![snd_food](https://cloud.githubusercontent.com/assets/10081924/15271751/95ed26d4-1a93-11e6-81bb-a27b083c285b.png)
