### ISSUE TITLE
Bugged Marsh Lurker

### ISSUE THREAD

**Issue by Lynchbox** [antisocial89/RealTBC_Issue_tracker#137]
Just inside the cave, can't attack him he won't attack me 
![ss 2016-05-11 at 07 33 23](https://cloud.githubusercontent.com/assets/19205497/15192028/490fdadc-17af-11e6-9f5a-6f6e92fff1a7.jpg)

**Comment by antisocial89** [comment]
Look at that sleepy little fuck, marsh lurker don't give a shit!

**Comment by Lynchbox** [comment]
Aha

**Comment by Saben65** [comment]
Should fix it. NPC was spawning too high off the ground.

```SQL
UPDATE creature SET position_z=41.11, orientation=5.799 WHERE guid=64845;
```

**Comment by antisocial89** [comment]
Will implement this one tomorrow.
