### ISSUE TITLE
Shadowmeld can't be used in combat

### ISSUE THREAD

**Issue by antisocial89** [antisocial89/RealTBC_Issue_tracker#149]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/soXZCxrA2OI/0.jpg)](https://youtu.be/soXZCxrA2OI "Video Title")

CLICK IMAGE TO WATCH VIDEO

**Comment by nairyo** [comment]
This is normal, combat shadowmelt is post TBC, please @antisocial89 confirm

**Comment by Saben65** [comment]
The video is taken from 2008 (TBC era).

**Comment by nairyo** [comment]
So this is normal?
