### ISSUE TITLE
Rare mob Ambassador Jerikar

### ISSUE THREAD

**Issue by Ajoli** [antisocial89/RealTBC_Issue_tracker#157]
Rare mob Ambassador Jerikar in Shadowmoon Valley almost gets killed by ashtounge workers nearby. 
![wowscrnshot_051316_192902](https://cloud.githubusercontent.com/assets/19350769/15256259/09b39642-1941-11e6-932d-f0667a92d98c.jpg)

**Comment by Ajoli** [comment]
He should not be attacked at all by the nearby mobs.

**Comment by Saben65** [comment]
The good ambassador appeared to be getting to friendly with a different faction. This should fix it.

```SQL
UPDATE creature_template SET FactionAlliance=1813, FactionHorde=1813 WHERE entry=18695;
```
