### ISSUE TITLE
Shadowhoof Summoners, entrance to black temple. 

### ISSUE THREAD

**Issue by Ajoli** [antisocial89/RealTBC_Issue_tracker#160]
Shadowhoof summoners are not attackable and wont aggro on anything and do not take damage from AoE abilities. 
![wowscrnshot_051316_193511](https://cloud.githubusercontent.com/assets/19350769/15256454/cf26c6ce-1941-11e6-9782-32dd1e8a97df.jpg)

**Comment by Saben65** [comment]
```SQL
UPDATE creature_template SET unitflags=32768 WHERE entry=22859;
```
