### ISSUE TITLE
Friendly NPCs in Enemy factions base.

### ISSUE THREAD

**Issue by Ajoli** [antisocial89/RealTBC_Issue_tracker#163]
![wowscrnshot_051316_201718](https://cloud.githubusercontent.com/assets/19350769/15257668/ba8cc0be-1947-11e6-91b1-bb3d9218ceaf.jpg)

**Comment by Saben65** [comment]
Blizzlike, this was taken from retail.

![friendly](http://i.imgur.com/JUK5cx7.png)
