### ISSUE TITLE
Seal of Justice

### ISSUE THREAD

**Issue by Yuvenz** [antisocial89/RealTBC_Issue_tracker#165]
Seal of Justice when released on a NPC doesn't slow them down as it should. I forgot how slow it was suppose to be from them fleeing but I think it was 50%.

![wowscrnshot_051316_204647](https://cloud.githubusercontent.com/assets/19213367/15265527/202064a4-194c-11e6-9e8e-4c5d04a05d1c.jpg)

**Comment by nairyo** [comment]
![screenshot from 2016-05-14 15 49 12](https://cloud.githubusercontent.com/assets/10081924/15266826/d1d82b6a-19eb-11e6-89f8-5db2cfcc0f80.png)
