### ISSUE TITLE
Wrong weapon on Bleeding Hollow Archer

### ISSUE THREAD

**Issue by antisocial89** [antisocial89/RealTBC_Issue_tracker#18]
Bleeding hollow archer has a staff equipped instead of proper bow.

**Comment by IanCrouch** [comment]
--Wrong weapon on Bleeding Hollow Archer #18
--https://github.com/antisocial89/RealTBC_Issue_tracker/issues/18
insert into `` (`entry`, `equipentry1`, `equipentry2`, `equipentry3`) values('1105','2530','0','18835');

--For some reason they have a static model set. This removes it and uses the one in creature_template
UPDATE creature
SET equipment_id ='0'
WHERE id = '17270';

**Comment by IanCrouch** [comment]
@ScaryRealTBC Tested locally, feel free.

**Comment by antisocial89** [comment]
Looks good. Closed
https://cdn.discordapp.com/attachments/152996050788024321/178950247731560449/unknown.png
