### ISSUE TITLE
Last boss in ramparts, loot chest in wrong location

### ISSUE THREAD

**Issue by antisocial89** [antisocial89/RealTBC_Issue_tracker#22]
Last boss loot chest spawns behind you where you came from in the main entrance to this section of the instance where it forks off between the two bosses.

**Comment by IanCrouch** [comment]
Wrote SQL to fix this.

**Comment by IanCrouch** [comment]
--Fel Cannons at forge camp: mageddon #24 
update creature_template
set AIName = 'EventAI'
where entry = '22461'

insert into `creature_ai_scripts` (`creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values('22461','1','0','100','0','0','0','0','0','21','0','0','0','0','0','0','0','0','0','0','0','Fel Cannon MK1 - Prevent Combat Movement on Spawn');
insert into `creature_ai_scripts` (`creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values('22461','9','0','100','3','0','40','2900','4900','11','36238','1','0','0','0','0','0','0','0','0','0','Fel Cannon MK1 - Cast Fel Fireball in combat');

**Comment by IanCrouch** [comment]
@ScaryRealTBC Tested Locally

**Comment by antisocial89** [comment]
Loot chest now spawns in the correct location. Closed
