### ISSUE TITLE
fel cannons at forge camp: mageddon

### ISSUE THREAD

**Issue by icywrath** [antisocial89/RealTBC_Issue_tracker#24]
they move towards you when they are not suppose to.

**Comment by IanCrouch** [comment]
Need to Flag Immobile in creature_template

**Comment by Saben65** [comment]
I believe the proper way to do this would be to disable combat movement in EventAI.

**Comment by IanCrouch** [comment]
@Saben65 Yeah, considering that flag is broken anyways.

**Comment by IanCrouch** [comment]
--fel cannons at forge camp: mageddon #24
--https://github.com/antisocial89/RealTBC_Issue_tracker/issues/24
`update creature_template
set AIName = 'EventAI'
where entry = '22461'

insert into `creature_ai_scripts` (`creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values('22461','1','0','100','0','0','0','0','0','21','0','0','0','0','0','0','0','0','0','0','0','Fel Cannon MK1 - Prevent Combat Movement on Spawn');
insert into `creature_ai_scripts` (`creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) values('22461','9','0','100','3','0','40','2900','4900','11','36238','1','0','0','0','0','0','0','0','0','0','Fel Cannon MK1 - Cast Fel Fireball in combat');`

**Comment by antisocial89** [comment]
They work! Fck yeah! Clo-ziiiiiiiiiiinnnng!
