### ISSUE TITLE
Healing Spells, Druid Class

### ISSUE THREAD

**Issue by Yuvenz** [antisocial89/RealTBC_Issue_tracker#31]
Lifebloom, Regrowth, Rejuvenation heal, but they do not heal or show healing at full hp when it should still show healing in combat log and show heal tics when at full hp.

**Comment by Saben65** [comment]
Not sure if this actually a bug.

>This is mostly dependent of classmechanics. Since druids HoT's will never overheal his HoT's stays on the target even at full health and if any dmg is taken then the HoT keeps healing him. I would say that there are hardly any class that is that good at raid healing. Just my 2 cents.
>
>Regards Långakniven

http://www.wowhead.com/forums&topic=80401.2/why-cant-i-heal-more-than-a-resto-druid-in-the-raids#p879365

**Comment by Weinrib** [comment]
Duplicate #7 
This is not a bug, please close.
Showing overhealing was added on 3.X.
