### ISSUE TITLE
[Karazhan] Archmage Leryda NPC_Text. Fix

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#43]
Removes unpopulated `NPC_Text` data from [Archmage Leryda](http://www.wowhead.com/npc=18253/archmage-leryda) that prevents players from talking to her (and thus starting the quest chain for the Kara rings.) She has another `Npc_Text` entry that contains her correct gossip that is properly attached to her gossip_menu.

```SQL
-- Remove incorrect text from Leryda
Code implemented and being tested
```

**Comment by Saben65** [comment]
Forgot to add portion to delete the entry from `gossip_menu`. Updated original query.

**Comment by antisocial89** [comment]
Archmage Leryda now has the appropriate text
