### ISSUE TITLE
[Karazhan] Bennett's Missing Gossip. Fix

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#46]
Currently [Bennett](http://www.wowhead.com/npc=16426/bennett) has no `gossip_menu` or `npc_text` in the DB.

```SQL
-- Add Bennett's Gossip
Code implemented and being tested
```

**Comment by Yuvenz** [comment]
All the fixes you're posting where are you getting them from and who is the author of the fixes ?

**Comment by antisocial89** [comment]
Bennett now has the appropriate text. Closed
