### ISSUE TITLE
[Steamvaults] Coilfang Engineer Incorrect Spawn Points. Fix

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#49]
NPCs spawn too far into the terrain, causing a "Target is out of Line of Sight" error. The correct spawn points are as followed (taken from sniff data).

```SQL
Code implemented and being tested
```

**Comment by antisocial89** [comment]
You will probably want to test this one as well. PM me for gm account.

**Comment by Saben65** [comment]
Looks good.
