### ISSUE TITLE
Flamerwalker Imp creature_linking Fix

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#51]
[Flamewalker Imps](http://www.wowhead.com/npc=19136/flamewaker-imp) and [Heckling Fel Sprites](http://www.wowhead.com/npc=18978/heckling-fel-sprite) should pull together in packs of 3. This should fix most the groups, further testing needs to be done to make sure it pulls the groups of 3 together, while not pulling extra groups (due to the 15 yard `search_range`.)

```SQL
Code implemented and being tested
```

**Comment by antisocial89** [comment]
Unfortunately they still do not pull together, did this work on your local server?

**Comment by Saben65** [comment]
I found one instance where they do not pull together on the live server, and it seems to be because the NPC is spawned farther away than on my local server.

```SQL
UPDATE `creature` SET `position_x`=148.838, `position_y`=2355.977, `position_z`=54.42 WHERE `guid`=68413;
```
I tried all the other spawns and they looked good. If you find any other issues, can you .gps the location?

**Comment by antisocial89** [comment]
Sure will - is this the pack closest to thrallmar?

**Comment by antisocial89** [comment]
Works perfect now. Closed
