### ISSUE TITLE
[Karazhan] Big Bad Wolf Pre-event dialogue issue

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#58]
https://www.youtube.com/watch?v=Ci32Aq3dMCM
Grandmother is suppose to go through the following dialogues.

- **Grandmother Gossip 1:** Hello, my child.
-- **Dialogue Option 1:** Oh, grandmother, what big ears you have.

- **Grandmother Gossip 2:** The better to hear you with, my child.
-- **Dialogue Option 2:** Oh, grandmother, what big eyes you have.

- **Grandmother Gossip 3:** The better to see you with, my child.
-- **Dialogue Option 3:** Oh, grandmother, what phat lewts you have.

- **BBW Yell:** The better to own you with!

Currently, she skips the first two dialogues and goes straight to the third one.

Additionally, if you continually talk to her, then hit escape to exit the gossip menu, the dialogue option will duplicate.

![Bug](http://i.imgur.com/yt1rMYQ.png)

**Comment by Saben65** [comment]
Believe I figured out the gossip duplication issue, it is an issue affecting most creatures with gossip.

In ScriptDevMgr.cpp line 264 uncomment

```C++
pPlayer->PlayerTalkClass->ClearMenus();
```

**Comment by antisocial89** [comment]
Implemented this, I never saw that when I checked, not sure where you saw it, might want to give it a test.

**Comment by Saben65** [comment]
It looks fixed, now to just add her proper gossip.

**Comment by Saben65** [comment]
Tested on local server and got it working. Sent the C++ update to antisocial, here is the SQL portion.

```SQL
-- Deletes old gossip text 3532005, adds correct gossip texts 19-21.
DELETE FROM gossip_texts WHERE entry IN (-3532005,-3532019,-3532020,-3532021); 
INSERT INTO `gossip_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `comment`) VALUES 
(-3532019, 'Oh, grandmother, what big ears you have.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'grandma GOSSIP_ITEM_GRANDMA1'),
(-3532020, 'Oh, grandmother, what big eyes you have.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'grandma GOSSIP_ITEM_GRANDMA2'),
(-3532021, 'Oh, grandmother, what phat lewts you have.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'grandma GOSSIP_ITEM_GRANDMA3');
```
