### ISSUE TITLE
Ally of the Netherwing

### ISSUE THREAD

**Issue by ScaryRealTBC** [antisocial89/RealTBC_Issue_tracker#73]
Quest works as intended, however, after completing, http://www.wowhead.com/npc=22113/mordenai does not give you the next quest to start your dailies: In Service of the Illidari (http://www.wowhead.com/quest=11013/in-service-of-the-illidari)

**Comment by Saben65** [comment]
Did you have 300 riding skill?

**Comment by ScaryRealTBC** [comment]
Closed. If you have the 300 riding skill it works as intended.
