### ISSUE TITLE
NPC: Unyielding Sorcerer

### ISSUE THREAD

**Issue by Krilliac** [antisocial89/RealTBC_Issue_tracker#79]
Constantly casted Frost Nova with no delay until it burned through all it's Mana.

**Comment by IanCrouch** [comment]
Looks like hes set to cast frost nova when someone is within 5 yards. Looking into a fix.

**Comment by IanCrouch** [comment]
-- Creature id: 16905
-- Only Frost nova once when fleeing at 15% and target is in melee ( > 5 Yards )
`UPDATE creature_template SET AIName='EventAI' WHERE entry=16905;
DELETE FROM creature_ai_scripts WHERE creature_id=16905;
INSERT INTO creature_ai_scripts VALUES 
('1690501','16905','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Set Phase to 0 on Evade'),
('1690502','16905','2','7','100','0','15','0','0','0','21','1','0','0','25','0','0','0','1','-47','0','0','Unyielding Sorcerer - Start Combat Movement and Flee at 15% HP (Phase 3)'),
('1690503','16905','2','0','100','0','15','0','0','0','11','11831','0','1','22','3','0','0','0','0','0','0','Unyielding Sorcerer - Cast Frost Nova and Set Phase 3 at 15% HP'),
('1690504','16905','3','11','100','1','0','0','0','0','23','0','0','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Set Phase 1 when Mana is above 30% (Phase 2)'),
('1690505','16905','9','0','100','0','0','5','10000','10000','34','0','0','0','11','11831','7','1','0','0','0','0','Unyielding Sorcerer - Ranged Movement at 5 Yards to Avoid Melee Combat'),
('1690506','16905','0','13','100','1','5000','9000','12000','15000','11','11829','1','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Cast Flamestrike (Phase 1)'),
('1690507','16905','9','13','100','1','0','5','1000','1000','21','1','0','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Start Combat Movement Below 5 Yards'),
('1690508','16905','9','13','100','1','5','15','1000','1000','21','0','0','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Prevent Combat Movement at 15 Yards (Phase 1)'),
('1690509','16905','9','13','100','1','25','80','1000','1000','21','1','0','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Start Combat Movement at 35 Yards (Phase 1)'),
('1690510','16905','3','13','100','1','15','0','1000','1000','21','1','0','0','23','1','0','0','0','0','0','0','Unyielding Sorcerer - Start Combat Movement and Set Phase 2 when Mana is at 15% (Phase 1)'),
('1690511','16905','9','13','100','1','0','40','2400','3800','11','9053','1','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Cast Fireball (Phase 1)'),
('1690512','16905','4','0','100','0','0','0','0','0','11','9053','1','0','22','1','0','0','0','0','0','0','Unyielding Sorcerer - Cast Fireball and Set Phase 1 on Aggro'),
('1690513','16905','1','0','100','0','0','0','0','0','21','0','0','0','0','0','0','0','0','0','0','0','Unyielding Sorcerer - Prevent Combat Movement on Spawn');`

**Comment by antisocial89** [comment]
No longer constantly casts frost nova
