### ISSUE TITLE
Quest: Journey to Honor Hold

### ISSUE THREAD

**Issue by IanCrouch** [antisocial89/RealTBC_Issue_tracker#81]
Item 28105 [Duron's Report] is sell-able and shouldn't be.

**Comment by Saben65** [comment]
Have you tried deleting your cache? I am unable to sell it on my local server.

**Comment by IanCrouch** [comment]
Still Sell able, Weird.  Is it like this on the realtbc db?

**Comment by IanCrouch** [comment]
Not sellable on realtbc db
