### ISSUE TITLE
Hellfire Combat Dummy Small is TO Small

### ISSUE THREAD

**Issue by Krilliac** [antisocial89/RealTBC_Issue_tracker#82]
http://prntscr.com/b187te

**Comment by Saben65** [comment]
Those are correct; however, there should be 4 more large ones by them. Will try to pull with sniff data.

**Comment by Saben65** [comment]
Suggested Fix: 
```SQL
-- Adds Missing combat dummies by Arch Mage Xintor
SET @CGUID := 151300;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID AND @CGUID+3;
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `DeathState`, `MovementType`) VALUES 
(@CGUID+0, 17059, 530, 1, 0, 0, -1309.493, 2774.156, -26.95394, 4.363323, 300, 0, 0, 2200, 0, 0, 0), -- 17059 (Area: 3546)
(@CGUID+1, 17059, 530, 1, 0, 0, -1304.588, 2771.275, -27.02782, 3.996804, 300, 0, 0, 2200, 0, 0, 0), -- 17059 (Area: 3546)
(@CGUID+2, 17059, 530, 1, 0, 0, -1321.134, 2771.165, -26.57714, 5.654867, 300, 0, 0, 2200, 0, 0, 0), -- 17059 (Area: 3546)
(@CGUID+3, 17059, 530, 1, 0, 0, -1315.754, 2774.218, -26.85213, 5.009095, 300, 0, 0, 2200, 0, 0, 0); -- 17059 (Area: 3546)

-- Makes small combat dummies not targetable.
UPDATE `creature_template` SET `UnitFlags`=33554688 WHERE `entry`=17060;
```

This will add the missing target dummies and make the smaller ones that are currently spawned not targetable (the proper unit flags were already set on the target dummies we spawned in).

**Comment by antisocial89** [comment]
Unfortunately this still seems to be an issue: https://cdn.discordapp.com/attachments/152996050788024321/178937657039126528/unknown.png

**Comment by Saben65** [comment]
Yeah it was working locally, you sure it got applied properly?

**Comment by antisocial89** [comment]
![image](https://cloud.githubusercontent.com/assets/17038716/15201759/f43f3d80-17b9-11e6-9526-de434bace4cf.png)
Alright, got them showing up now however the combat dummy's are still targetable:

![image](https://cloud.githubusercontent.com/assets/17038716/15201766/13740dac-17ba-11e6-98b5-e6676b92e520.png)

**Comment by Saben65** [comment]
Coulda swore I put the query for those in there. Will fix it when I get back home.

**Comment by Saben65** [comment]
![dummy](http://i.imgur.com/1tEYmNW.png)

Looks good to me.

**Comment by antisocial89** [comment]
You can't target the small ones?

**Comment by Saben65** [comment]
Correct. With or without GM on, I cannot target the small ones on the live server.
