### ISSUE TITLE
Spikebreaker Post Gossip

### ISSUE THREAD

**Issue by IanCrouch** [antisocial89/RealTBC_Issue_tracker#83]
Lot's of NPCS @ Spikebreaker Post say
Greetings <name>.

Will need to add or link their gossip.

**Comment by Saben65** [comment]
Are there any that aren't on this list?

https://github.com/antisocial89/RealTBC_Issue_tracker/issues/44

Dunno if that fix was applied to the live server yet.

**Comment by IanCrouch** [comment]
Will double check sir

**Comment by IanCrouch** [comment]
Yup looks like thats all of them, Closing as duplicate of #44
