### ISSUE TITLE
[Terrorkar] Double Dreadfang Widow spawn. Fix

### ISSUE THREAD

**Issue by Saben65** [antisocial89/RealTBC_Issue_tracker#96]
```SQL
-- Dreadfang Widow spawn fix
Code implemented and being tested
```

Removes one copy of the creature that was double spawned, and moves the other slightly to data sniffed from retail.

**Comment by antisocial89** [comment]
This is likely something you will want to test yourself as I don't know how they used to look, PM me in Discord with account credentials so I can get you a GM account created

**Comment by Saben65** [comment]
Issue is fixed.
